#   CustomBar Made
#                 By
#                     SuperKali Updated And fixed by @DakerOmar
#

#Text you will see on the server, {tps}, {load}, {players}, {max_players}, {line}, {x} {y} {z}, {coins}, {MOTD}, {faction}, {name}, {time}, {kills}, {deaths}, {ping}, {group} and & for color
#{coins} You need to use EconomyAPI to show money!

#Text to show on the server in the custom bar!
text: "&4AversionPE
&dIGN: &f{name} &6Rank: &f{group}
&aBalance: &f{coins} &cFaction: &3{faction}"

#Time that the message is updated, P.S Leave the default 5!
time: 5

#TimeZones configuration, link: https://www.timeanddate.com/time/zones , Default timezone Central European!
timezone: CET

#TimeZones Format Configuration Example (H:i) Format 24 hours (h:i A) Format 12 hours, Default formatime 24 hours!
formatime: H:i
#KillChat for show kills and deaths!
Allow.KillChat: true
